# Generated by Django 2.1.7 on 2019-04-11 08:52

import candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_candidate_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=candidates.models.candidate_image_path, verbose_name='圖片'),
        ),
    ]
